通知を受け取るためにStarではなくWatchすることを推奨する記述を追加 #32
jawordpressorg/ideas pull request #35
Opened 2018-06-20 23:40 UTC by musus

2018-06-20 23:43 UTC, ixkaito approved these changes

2018-06-21 02:32 UTC, torounit commented
@musus https://raw.githubusercontent.com/jawordpressorg/ideas/images/ideas-screenshot-001.png

の画像ってどこに居ます？

2018-06-21 06:00 UTC, musus commented
imagesブランチを切ったのでそれを先にマージしてもらえればと！

2018-06-21 06:26 UTC, miya0001 requested changes

2018-06-21 06:37 UTC, miya0001 commented on README.md
> +![Wotchのクリック](https://raw.githubusercontent.com/jawordpressorg/ideas/images/ideas-screenshot-001.png)
あっ、もしできなかったらこちらでやるのはウェルカムなので言ってください。:blush:

2018-06-21 17:56 UTC, miya0001 commented
@musus  これコンフリクト直せます？

2018-06-21 17:57 UTC, miya0001 commented
@musus あとタイポも。ｗ

2018-06-22 10:49 UTC, miya0001 approved these changes

2018-06-22 10:49 UTC, miya0001 commented
Thanks 😊

2018-06-22 10:50 UTC, merged